README.md

`react-native link` seems to work (at least for some projects) to set up android.
Add a couple sentences to the readme to communicate that this is a possible option.

Mention 'react-native link' in README for android installation

---

README.md

Our default podspec pulls in React 0.11, which can cause build failures if React isn't already overridden in the target project's Podfile.

Update README to include details about updating Podfile for React dependencies

---

react-native-heap.podspec

This allows us to send events to localhost, which we use for testing.

Upgrade Heap dependency to 5.1.0.

---

js/Heap.js

`View` components show up in the hierarchy in dev builds, but not prod builds, and aren't actually relevant to the overall component hierarchy.  Leave `View`s out of the hierarchy.

Ignore 'View' components in hierarchy

---

js/Heap.js
package.json

The main reason this dependency was originally included was to restrict the platforms where rnheap would run to only iOS (since android wasn't implemented).  Now that android is also supported, we can remove this dependency.

Remove react-native-package dependency

---

js/Heap.js

It seems like `elementType` isn't present on fiberNodes for certain versions and/or configs, but `type` does seem to be present regardless of whether `elementType` is present.

Get component name from 'type' instead of 'elementType'

---

README.md

When installing `react-native-heap`, one needs to add certain plugins to their `.babelrc`.  Add instructions for this.

Add README instructions for necessary babel plugins

---

examples/TestDriver/package-lock.json
examples/TestDriver/package.json
package.json

`babel-plugin-add-react-displayname` needs to be in an app's `.babelrc` in order for hierarchies to include meaningful component names, but it's not currently a package dependency.  This means that a dev would need to `npm install babel-plugin-add-react-displayname` themselves in order to get autotrack.
Instead, make `babel-plugin-add-react-displayname` a dependency of the `react-native-heap` package.

Add babel-plugin-add-react-displayname as package dependency

---

js/Heap.js
js/util/__tests__/extractProps.spec.ts
js/util/extractProps.ts

For functional components, the fiber node has no `stateNode`, so we should get included props from `memoizedProps` instead.

Use memoizedProps when stateNode is null

---

e2e/README.md
e2e/firstTest.spec.js
e2e/init.js
e2e/mocha.opts
package-lock.json
package.json

To make it easier to keep e2e tests in-sync with the library, we're moving the detox tests from the internal repo to the public repo.
Because the test assertions depend on internal utils, the tests can only be run by those with access to the internal repo (i.e. Heap engineers).
Additional details are in the corresponding PR in the internal repo.

Move detox tests from internal repo

---

examples/TestDriver/package-lock.json
js/util/__tests__/extractProps.spec.ts
js/util/extractProps.ts

Currently, there is no way to attach prop capture configs to functional components, since we look for `heapOptions` on `stateNode`s, which do not exist on functional component instances.
With a functional component like
```
const Foo = (props) => {
return (
<some jsx>
);
};
```
a `heapOptions` object can now be added by doing
```
Foo.heapOptions = {
<options>
}
```
This would lead to `heapOptions` showing up on the `fiberNode.type` object.
While it's technically possible to allow this for class components, doing so could be potentially error-prone, since it would provide two different ways to declare heap options that wouldn't be close to each other in code.  E.g. a dev might add heap options as a static prop on a class component when heap options already exist through `Foo.heapOptions = …

Allow prop capture configs to be attached to functional components

---

js/Heap.js

Some versions of fiber don't have `elementType`, but they generally seem to have `type`, so use that instead

Use `type` instead of `elementType` for targetText

---

js/util/__tests__/extractProps.spec.ts
js/util/extractProps.ts

See https://github.com/heap/react-native-heap/pull/38 for additional context.
`pick` from the `lodash` package has different behavior than `lodash.pick`.  This behavior does what we prefer for allowing props to be included by key path, so we can use that instead.

[HEAP-8030] Allowing specifying prop by flattened key path

---

e2e/basics.spec.js
e2e/propExtraction.spec.js
examples/TestDriver/ios/TestDriver/AppDelegate.m
js/propExtractorConfig.ts
js/util/extractProps.ts

Adds a wildcard category to the built-in property extractor configuration so that we can extract testID on any component that has one.

Add wildcard config, and extract testID

---

e2e/basics.spec.js
e2e/propExtraction.spec.js
examples/TestDriver/android/app/build.gradle
examples/TestDriver/android/app/src/main/java/com/testdriver/MainApplication.java
examples/TestDriver/android/settings.gradle
examples/TestDriver/ios/Podfile
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/ios/TestDriver.xcodeproj/project.pbxproj
examples/TestDriver/ios/TestDriver/AppDelegate.m
examples/TestDriver/package.json
examples/TestDriver/src/topNavigator.js
js/Heap.js
js/autotrack/reactNavigation.js
js/autotrack/touchables.js
js/propExtractorConfig.ts
js/util/extractProps.ts
package-lock.json
package.json

This PR adds the ability wrap a React Navigation AppContainer with a Heap component and autotrack any changes in the route.  This also refactors the existing autotrack for Touchables into its own module so the main Heap module stays tidy.
- Version bump to 0.2.0-alpha3

Add autotrack support for React Navigation

---

e2e/00_initial.spec.js
e2e/basics.spec.js
e2e/nav.spec.js
e2e/propExtraction.spec.js
e2e/rnTestUtilities.js
examples/TestDriver/src/pages/basics.js
examples/TestDriver/src/pages/initial.js
examples/TestDriver/src/pages/nav.js
examples/TestDriver/src/pages/propExtraction.js
examples/TestDriver/src/sentinelUtilities.js
examples/TestDriver/src/topNavigator.js

The first commit refactors the existing tests slightly, renaming some of the files and moving the navigationOptions into a common spot in the navigator.  The second commit adds the tests for navigation, and the pages to support it.  To capture the initial navigation event, there is a new "initial" page with just a single test.

Add detox e2e tests for React Navigation

---

ios/RNHeap.xcodeproj/project.pbxproj
ios/Vendor/Heap.h
react-native-heap.podspec

Currently, the binary lib gets pulled down from Cocoapods, but this makes it difficult to do a manual integration if you're allergic to Cocoapods.  This change makes it so that the binary is included, and rejiggers the podspec to link the binary directly.
Tested manually, both with Cocoapods and a manual linking setup.

Vendoring native Heap lib instead of CP dependency

---

examples/TestDriver/android/app/build.gradle
examples/TestDriver/android/build.gradle

Detox was upgraded in #64; this transition caused breaking changes in
the Android TestDriver app which weren't addressed. This change gets
the Android build working again.
https://heap.slack.com/archives/CFB8RN9A9/p1553899644006100

Get Android TestDriver working with new Detox version.

---

e2e/00_initial.spec.js
js/autotrack/reactNavigation.js

- React navigation uses one of `Navigate/{NAVIGATE,BACK,POP}` to
represent various navigation-related actions. We capture these in the
`type` custom prop when intercepting these actions in
`onNavigationStateChange`.
- We create the initial navigation action that fires when the app is
loaded, and this was not assigned an action type so far, which makes the
event more difficult to distinguish.
- This commit picks `Navigate/INITIAL` as the identifier for this
initial navigation event.
- The event ends up looking like this in Kafka:
```json
{
"meta": {
"isFullEvent": true,
"received_at": "1554802335285"
},
"type": "event",
"body": {
"pageview_id": "8638062634366642",
"session_id": "1448579568939958",
"user_id": "3430884887124024",
"app_id": "11",
"library": "ios",
"type": …
```

Use `Navigate/INITIAL` for the initial react-navigation action.

---

android/build.gradle

Fixes issue where parent project on a different sdkVersion wouldn't be able to build this library

android: use parent project's version information if available

---

examples/TestDriver/android/app/src/androidTest/java/com/testdriver/DetoxTest.java

The Detox upgrades implemented in 75544e713bc0a171a6c0bea42507f3ffb7cb4a69 were incomplete; this gets Detox+Android working locally.

[Slack link] Fix Detox+Android tests.

---

examples/TestDriver/android/app/build.gradle
examples/TestDriver/android/app/src/main/java/com/testdriver/MainApplication.java
examples/TestDriver/android/settings.gradle
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/ios/TestDriver.xcodeproj/project.pbxproj
examples/TestDriver/package.json
examples/TestDriver/src/pages/basics.js
instrumentor/src/index.js
instrumentor/test/fixtures/is-switch/code.js
instrumentor/test/fixtures/is-switch/output.js
instrumentor/test/index.js
js/Heap.js
js/autotrack/common.js
js/autotrack/switches.js
js/autotrack/touchables.js

Autotrack when a `Switch` is toggled.
This covers both the NativeBase and React Native `Switch` components (NativeBase delegates to the RN `Switch).
This PR includes a refactor of the `autotrack` folder, in which logic used by autotrack methods for both `Switch`es and `Touchable`s was pulled into a separate `common.js` file.
~e2e tests are in progress and will likely be pushed up later today or early-ish tomorrow.~
Will open e2e tests in a separate PR, since these depend on a separate test util refactor.

Autotrack for RN Switch components

---

e2e/basics.spec.js
e2e/propExtraction.spec.js
js/util/extractProps.ts

- We have to special-case this a bit because React doesn't allow access to
the `key` property without a yellowbox warning popping up.
- e2e tests are passing locally.
https://reactjs.org/docs/lists-and-keys.html

[HEAP-8473] Capture the `key` property for list items that have it set.

---

e2e/basics.spec.js
e2e/propExtraction.spec.js
e2e/rnTestUtilities.js

Currently, our RN test utils are hard coded to assert the props `touchableHierarchy` and `targetText`.  This doesn't work when these props are different or not present (e.g. `targetText` is not a prop for `Switch` components, since these don't have any inner text).
Instead, we should take a generic `expectedProps` object, and expand this to the correct format for ios/android when making the event assertion.
~Note: this has been tested on iOS, but not on android (having trouble with my local android build for TestDriver), and so should not yet be merged~.  This has now been successfully tested on android

Refactor RN test utils to accept generic props

---

e2e/basics.spec.js
examples/TestDriver/src/pages/basics.js
instrumentor/src/index.js

This PR includes:
* e2e tests for switches
* a fix for a bug that was uncovered by the tests
Specifically, the bug occurred when the bundler generated bundles for both platforms within the same process.  Because the `instrumentedComponentNodes` set is not re-initialized for each new platform, the following happens:
* generate bundle for iOS
* mark 'Switch' as visited in `instrumentedComponentNodes`
* generate bundle for android
* 'Switch' is contained in `instrumentedComponentNodes`, so don't instrument `Switch`
By adding the `path` object to the set, rather than the string representation 'Switch', the key will be different between platforms, but still the same for subsequent visits to the same node within the same platform (i.e. keys will be different between iOS and android, but the key …

E2E tests for RN Switch component

---

examples/TestDriver/android/app/build.gradle
examples/TestDriver/android/app/src/main/java/com/testdriver/MainApplication.java
examples/TestDriver/android/settings.gradle

While attempting to "fix" `TestDriver` in https://github.com/heap/react-native-heap/pull/71, an extra `react-native link react-native-gesture-handler` was performed, which inserted duplicate code, and led to runtime errors related to the code duplication.
Remove this extra code.
We should also consider looking into getting `react-native link` to recognize that this package is already linked (although with autolinking on the horizon, it's unclear if this would really be worth it)

Remove code inserted by extra 'react-native link' for the RN Gesture Handler

---

js/Heap.js
js/__tests__/Heap.spec.js
js/autotrack/reactNavigation.js
js/util/bailer.ts

- Errors are swallowed in production and surfaced in debug builds.
- This covers the public API and the autotracking code.

[HEAP-8830] Don't allow errors thrown by the Heap library to crash the client app.

---

js/Heap.js

This isn't currently necessary to prevent crashes (since the `bailOnError` method will catch any errors), but once `bailOnError` actually bails (rather than just swallow errors), this will be necessary to keep Heap from bailing when the argument to these methods is `null` or `undefined`.

[HEAP-8474] Set AUP/AEP props to '{}' if null

---

README.md
docs/android-setup.md
docs/ios-setup.md

I split iOS-specific and Android-specific instructions into separate files; doing this in one file was getting a bit unwieldy.

[HEAP-9052] Update documentation to cover auto-initialization.

---

js/Heap.js
js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/heapIgnore.js

One HeapIgnore use case we expect to be somewhat common is to ignore a component subtree's target text and nothing else.  With the current `HeapIgnore` component, this would look like:
```
<HeapIgnore
allowInteraction={true}
allowInnerHierarchy={true}
allowAllProps={true}
>
<MySensitiveTextComponent />
</HeapIgnore>
```
To reduce the boilerplate for such a component, this PR adds a `HeapIgnoreTargetText` convenience component that is the equivalent of the above snippet, without the config:
```
<HeapIgnoreTargetText>
<MySensitiveTextComponent />
</HeapIgnoreTargetText>
```
Note that one side effect of this particular implementation is that the presence of the `HeapIgnoreTargetText` component leads to a `HeapIgnoreTargetText;|HeapIgnore;|` in the resulting component hierarchy, rather than …

[HEAP-9245] Add 'HeapIgnoreTargetText' convenience component

---

js/autotrack/reactNavigation.js

Currently, the HOC for react navigation autocapture (`withReactNavigationAutotrack`) doesn't pass through props.  This effectively disallows passing props into the navigation container wrapped by the HOC.
Pass props to the container wrapped by the HOC.
Fixes #91

Pass through props for React Navigation autocapture HOC

---

e2e/heapIgnore.spec.js
e2e/rnTestUtilities.js

The `findEventInRedisRequests()` method used for assertions that an event did _not_ occur on iOS doesn't work for android, so add an equivalent spec for android that uses the `findAndroidEventInRedisRequests()` method instead.

Fix android assertion on HeapIgnore

---

e2e/nav.spec.js
e2e/propExtraction.spec.js
examples/TestDriver/App.js
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/src/pages/nav.js
js/autotrack/reactNavigation.js

This is needed for users using the [Navigating without navigation prop](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html) pattern.
The changes made in this PR generally follow the instructions in the [Forwarding refs to HOCs documentation](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components), although there's some additional logic caused by the HOC needing the inner ref, as well (setRef copied from [here](https://github.com/facebook/react/issues/13029#issuecomment-497629971)).
~TODO: Add tests that would fail if the ref isn't forwarded~. Done

[HEAP-9449] Perform ref forwarding for react nav HOC

---

e2e/00_initial.spec.js
e2e/basics.spec.js
instrumentor/src/index.js
package.json

Currently, our linting commands (and thus CI) only checks the `js/` and `examples/` folders.  As a result, the `instrumentor/` and `e2e/` folders have become unformatted.
Update the `lint` command to also lint `instrumentor/src/` (to avoid the test files) and `e2e/`, and format these folders accordingly.

Lint all source folders

---

examples/TestDriver/package.json
package.json

There seems to be a bug in later versions of detox that are causing android tests to hang when I run locally.  Pin detox to a specific version instead of using `^`.

Pin detox version

---

examples/TestDriver/App.js
js/autotrack/reactNavigation.js

Some customers were experiencing a `Cannot read property 'nav' of null` error with the react nav HOC.  This is most likely caused by some sort of re-rendering or ref update of some top-level components, including the navigation container wrapped by our HOC.
I have not repro'd this issue via a real-life use case, but doing `this.setState()` seems to force the ref update.  Confirmed that these changes resolve the issue for this specific case.
Note: while this example led to the component ref getting updated to the same value as the previous ref (i.e. getting updated from `ref1` -> `null` -> `ref1`), it's possible that some cases of ref updating may be due to actually different refs (e.g. `ref1` -> `null` -> `ref2`).  If this were to be the case, this would lead to potentially duplicated …

[HEAP-8753] Fix null reference issue in react nav HOC

---

e2e/basics.spec.js
e2e/nav.spec.js
js/autotrack/common.ts
js/autotrack/reactNavigation.js
js/util/navigationUtil.ts

This adds `path` and `screenName` props to all autocaptured events (e.g. `touchableHandlePress`, etc.), where `path` is the full path of the current screen route (e.g. `Nav::MainStack::Base`), and `screenName` is the individual name of the current screen route (e.g. `Base`).
This does *not* include these props on custom tracked events.

[HEAP-9951] Capture screen name props for autocaptured events

---

ios/RNHeap.xcodeproj/project.pbxproj
react-native-heap.podspec

With `/usr/bin/ruby`, it uses the system's ruby version. If the user has `rvm` or `rbenv` to manage the ruby versions and they don't use the the system's one, the script might fail because dependencies issues:
```
[10:39:44]: ▸ Ignoring json-2.2.0 because its extensions are not built.  Try: gem pristine json --version 2.2.0
[10:39:44]: ▸ Ignoring unf_ext-0.0.7.6 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.6
[10:39:44]: ▸ /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
[10:39:44]: ▸ 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[10:39:44]: ▸ …
```

Remove `/usr/bin/ruby` when executing settings script.

---

instrumentor/src/index.js
instrumentor/test/fixtures/is-scroll-view-createreactclass/output.js
instrumentor/test/fixtures/is-scroll-view-extends-component/output.js

~Leaving this as a draft until I confirm the most recent changes work on both RN 0.57.5 and RN 0.60.4, but otherwise ready for review~.  I haven't been able to get RN 0.60.4 to build Android on the test app, but I got an upgraded iOS build to a state in which unit+e2e tests pass on RN 0.60.4.  Because this was an issue with the babel plugin (not native code), I think it's reasonable to go ahead and merge.
On newer versions of react native (after the `ScrollView` component was switch from using a mixin and `createReactClass` to extending `React.Component`), the referenced `this` is incorrect, and causes errors upon `onMomentumScrollEnd()`.
Change the `ScrollView` instrumentation to use `t.thisExpression()` instead of `t.identifier('_this')`.
TODO: look into using `t.thisExpression()` for …

[HEAP-10061] Fix scrollview `this` issue

---

e2e/basics.spec.js
e2e/heapIgnore.spec.js
e2e/nav.spec.js
e2e/propExtraction.spec.js
e2e/rnTestUtilities.js

A few small test improvements (best reviewed commit-by-commit):
* Refactor page-level hierarchies into constant
* Only wait for iOS to flush on iOS tests (reduces android test run times by minutes)
* Fix nesting for Basics (previously, a failed `before` for autocapture tests wouldn't prevent autocapture tests from running)
* Pull redis `flushall()` into promisified util
* Reduce android flakes caused by the keyboard being in the way when a button should be tapped

Grab bag of test improvements

---

PULL_REQUEST_TEMPLATE.md

We've regularly forgotten to do things like update the changelog when adding a new feature (vs updating the changelog when we're about to do a release), so add a basic PR template including tasks like "update the changelog"

[HEAP-9338] Add PR template

---

CHANGELOG.md
e2e/basics.spec.js
e2e/heapIgnore.spec.js
e2e/propExtraction.spec.js
examples/TestDriver/src/pages/heapIgnore.js
js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/heapIgnore.js
js/autotrack/reactNavigation.js
js/util/hocUtil.js

Use `displayName` conventions for higher-order components (described [here](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging)).
This will break any event definitions relying on the component naming of `HeapNavigationWrapper` (for `withReactNavigationAutotrack`) or `_class` (for `withHeapIgnore`).  These aren't semantically meaningful, and likely aren't used for event def.
* Updated all detox test to use new display names in hierarchies.
* Updated HeapIgnore unit test to use new display names in hierarchies.
* Added detox test case for HeapIgnore HOC display name.

[HEAP-10464] Use correct conventions for HOC display name

---

examples/TestDriver/android/app/build.gradle
examples/TestDriver/package.json

At some point, the TestDriver test app started using a newer version of `react-native-gesture-handler`, which caused build issues on android.  Pinned this dep's version to an earlier version, and updated compile options to address other build issues that arose.
Detox tests.

Fix test app detox android build

---

__mocks__/react-native.js
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
ios/RNHeap.m
js/Heap.js
js/__tests__/Heap.spec.js

Refactor bridge methods to prep for the frameworks API that will be provided by the native libs.
Existing tests

Refactor bridge and methods to look like frameworks API

---

e2e/basics.spec.js
e2e/nav.spec.js
e2e/rnTestUtilities.js
ios/RNHeap.m
ios/Vendor/Heap.h
js/autotrack/reactNavigation.js

* Upgrade the vendored iOS Heap dependency to 6.5.0-alpha.1
* Switch the native iOS methods the bridge uses from custom track to the framework track methods provided in Heap iOS v6.5.0
* Change the `type` field in navigation events to `action`, since `type` is reserved for the event name
* Update tests + test utils to use `source` and `sprops` pixel params.
This will introduce inconsistency between how iOS and Android events are sent and processed server-side, so merging into `feature/rnfcl` for now.
Updated + ran detox tests, and observed correct events coming to kafka.

[HEAP-11501] Use iOS Framework track methods

---

e2e/basics.spec.js
e2e/heapIgnore.spec.js
e2e/nav.spec.js
e2e/propExtraction.spec.js
e2e/rnTestUtilities.js
instrumentor/src/index.js
instrumentor/test/fixtures/is-scroll-view-createreactclass/output.js
instrumentor/test/fixtures/is-scroll-view-extends-component/output.js
instrumentor/test/fixtures/is-switch/output.js
instrumentor/test/fixtures/is-text-input/output.js
js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/common.ts
js/autotrack/reactNavigation.js
js/autotrack/scrollViews.js
js/autotrack/textInput.js
js/autotrack/touchables.js
js/util/navigationUtil.ts

Revised event type/prop names:
* `touchableHandlePress`/`touchableHandleLongPress` -> `touch`
* Added `isLongPress` to `touch` events to differentiate
* `_handleChange` -> `change`
* `touchableHierarchy` -> `hierarchy`
* All other event type/prop names converted from `lowerCamelCase` to `snake_case`.
Updated existing tests, and observed incoming pixel requests.

[HEAP-11507] Revise names of event types + props

---

e2e/basics.spec.js
js/Heap.js
js/__tests__/Heap.spec.js
js/util/__mocks__/navigationUtil.js

For manual track calls, include screen props (`screen_name`, `path`) as contextual source props.
Updated existing tests

[HEAP-11523] Send screen props as contextual framework props

---

android/build.gradle
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
e2e/basics.spec.js
e2e/rnTestUtilities.js
examples/TestDriver/android/build.gradle

* Switch the native Android methods the bridge uses from custom track to the framework track methods provided in https://github.com/heap/heap/pull/25075
* Updated tests to use the framework event format
* Changed the Heap native android SDK dependency to point to the `1.3.0-SNAPSHOT` version hosted on our S3 maven repo
~Note that this uses WIP changes from the android lib.  The android lib changes will need to be merged + released, and the react-native-heap lib's android dep will need to be upgraded in order for this to work.~
Updated existing detox test cases

[HEAP-11558] Use Android Framework track methods

---

e2e/basics.spec.js
e2e/rnTestUtilities.js
js/autotrack/touchables.js

This fixes a few names that were missed in https://github.com/heap/react-native-heap/pull/149
Added assertions to detox test cases

[HEAP-11507] Revise additional names of event types + props

---

e2e/basics.spec.js
e2e/heapIgnore.spec.js
e2e/nav.spec.js
e2e/propExtraction.spec.js
e2e/rnTestUtilities.js
js/__tests__/Heap.spec.js
js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/common.ts
js/autotrack/reactNavigation.js
js/util/navigationUtil.ts

Renames hierarchy to react_hierarchy and path to screen_path due to conflicts with the web `hierarchy` and `path` properties on the frontend.  This was originally expected to be a non-issue, since these fields would be from RN, and the web fields would be from web, but this doesn't seem to be the case.
Updated test cases

Rename conflicting field names

---

CHANGELOG.md
android/build.gradle
examples/TestDriver/android/build.gradle

Bump the android dep to the actual release of v1.3.0
Ran tests

[HEAP-11566] Bump android to the released v1.3.0

---

e2e/basics.spec.js
e2e/heapIgnore.spec.js
e2e/propExtraction.spec.js
js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/common.ts

Update the hierarchy format to include an `@` before the component name.  This is what web, android, and ios do for hierarchies, and is required if we want to enable the `hier` operator (i.e. CSS-style matchers) in event definitions in the UI.
This _may_ be a breaking change for some event definitions, but only in the sense that the string used for matching might need to be different; event definitions will be broken and will need to be updated as part of an RNFCL upgrade anyway.  However, instead of being able to copy-paste a "touchableHierarchy contains `MyComponent;|MyOtherComponent`", users would need to manually update the string to `@MyComponent;|@MyOtherComponent` if using "React Native Hierarchy contains ...", or `MyComponent MyOtherComponent` (preferred) if using the target field …

Update React Hierarchy Format

---

e2e/basics.spec.js
examples/TestDriver/src/pages/basics.js
js/autotrack/touchables.js

If a user long-presses a `Touchable` component, and the `Touchable` does not have an `onLongPress` handler, we’ll fire two touch events - one when the long press event fires (which happens after a brief delay), and one when the touch is released.
This used to matter less, since the long press and short press events had different types (`touchableHandlePress` and `touchableHandleLongPress`), so users would most likely just define their event on `touchableHandlePress` (thus reducing the likelihood of duplicated events manifesting in the virtual layer).
However, with the RNFCL changes, short and long presses are combined into a single touch event, with an `is_long_press` prop differentiating the two.  Since it would be unreasonable to expect all customers to specify a filter on …

De-duplicate long press and short press events

---

CHANGELOG.md
examples/TestDriver/App.js
js/autotrack/reactNavigation.js

Currently, if an `onNavigationStateChange` handler is passed to the React Navigation autocapture HOC, that handler will get called instead of the handler defined within the HOC.  So if someone is manually tracking screenviews using the [instructions provided by React Navigation](https://reactnavigation.org/docs/en/screen-tracking.html), our React Navigation autocapture won't work.
Delegate to the `onNavigationStateChange` passed to the HOC within the HOC's `onNavigationStateChange` handler.
Changed test app to pass a `onNavigationStateChange` handler to the HOC.

[HEAP-12315] Delegate React Navigation onNavigationStateChange

---

CHANGELOG.md
ios/Vendor/Heap.h

Bump vendored iOS SDK to 6.5.1.
Existing tests

[HEAP-11565] Vendor iOS v6.5.1

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
package-lock.json
package.json

Bump version to 0.9.0
Currently blocked on updating the changelog with the upgrade guide.

[HEAP-11800] Bump version to 0.9.0

---

e2e/mocha.opts
examples/TestDriver/ios/TestDriver/AppDelegate.m

Make detox e2e tests on iOS less flakey by ignoring native iOS events, and increasing the mocha timeout.

Make e2e tests less flakey

---

CHANGELOG.md
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
js/Heap.js

`NavigationUtil.getScreenPropsForCurrentRoute()` returns `null` if there are no contextual navigation props, but the `manuallyTrackEvent` in the Android `RNHeapLibraryModule` expects a non-null value.
Fixes https://github.com/heap/react-native-heap/issues/165.
Manually repro'd bug by removing `withReactNavigationAutotrack` HOC wrapper, then manually tested after fixing bug.

Don't crash when Heap.track() is called and contextual props aren't present

---

CHANGELOG.md
ios/Vendor/Heap.h

Vendor v6.5.3 of the Heap iOS SDK dependency
Ran detox tests for iOS

Vendor iOS 6.5.3

---

CHANGELOG.md
js/autotrack/__tests__/common.spec.js
js/util/__tests__/extractProps.spec.ts
js/util/extractProps.ts

Currently, if the value of a prop to be captured is an object with a circular reference, or a React element (which is a special case of objects with circular refs), our library will blow the call stack. Example of React element prop:
```
<ListItem rightTitle={<Text>Foo</Text>} />
```
Correct this two ways:
* Set a `maxDepth` before attempting to flatten a prop value to avoid circular refs.
* Set the prop value to be `React.element` when the prop is a valid React element.
In the future, we can set the prop value of React elements to be more representative of the actual element, but that's outside the scope of this PR.
Added unit tests

Fix prop capture for react elements and circular refs

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
package-lock.json
package.json

Bump the version of RNHeap to 0.9.1.
Merging this is blocked on https://github.com/heap/react-native-heap/pull/170 and running detox tests again.

Bump to version 0.9.1

---

e2e/basics.spec.js
js/Heap.js
js/__tests__/Heap.spec.js
js/autotrack/__tests__/common.spec.js
js/autotrack/common.ts
js/util/contextualProps.ts
js/util/metadataPropUtil.ts
js/util/navigationUtil.ts

Enrich events with telemetry metadata.  Specifically, the RNHeap SDK version and whether the React Navigation HOC has been instantiated.
Update e2e tests
- [] ~If this is a bugfix/feature, the changelog has been updated~ (N/A)

Telemetry metadata enrichment

---

CHANGELOG.md
__mocks__/react-native.js
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
e2e/basics.spec.js
examples/TestDriver/src/pages/basics.js
ios/RNHeap.m
js/Heap.js
js/__tests__/Heap.spec.js

Adds a `getUserId()` method to the Heap API that returns a promise that resolves to the current userID (managed by the underlying native Heap SDK).
Because calls over the react native bridge to the native modules happen asynchronously, this method returns a promise.  For example, to get the user ID, you might do,
```
Heap.getUserId()
.then(userId => {
console.log(`User ID is ${userId}`);
});
```
or, if you're using `async/await`, you might do
```
const userId = await Heap.getUserId();
console.log(`User ID is ${userId}`);
```
It is _not_ possible to do something like
```
console.log(`User ID is ${Heap.getUserId()}`)
```
because `Heap.getUserId()` will return a yet-to-be-resolved promise.
* Add e2e Detox tests
* Add unit tests

[HEAP-9394] Add getUserId method

---

CHANGELOG.md
index.d.ts

Adds TS typings for `resetIdentity()` and `getUserId()` methods.
Ran `tsc index.d.ts` to check compilation.
- ~[ ] Detox tests pass (only Heap employees are able run these)~ N/A.

[HEAP-13861] Update index.d.ts typings with resetIdentity and getUserId methods

---

CHANGELOG.md
android/build.gradle
examples/TestDriver/android/build.gradle

Bump Android dependency from v1.3.0 to v1.6.0.
Existing tests

[HEAP-14317] Bump Android dep to 1.6

---

e2e/basics.spec.js
e2e/rnTestUtilities.js
js/autotrack/reactNavigation.js

Add contextual props to screenview events.  This mostly just ensures that the RNHeap version is included on screenview events.
E2E detox tests.
- ~[ ] If this is a bugfix/feature, the changelog has been updated~ Not a feature.

[HEAP-13941] Add SDK version info to screenviews

---

CHANGELOG.md
ios/Vendor/Heap.h

Bump Heap iOS SDK dependency from version 6.5.3 to 6.7.0.
Detox tests

[HEAP-14089] Bump iOS dependency to version 6.7.0

---

CHANGELOG.md
js/autotrack/heapIgnore.js

Improve support for HeapIgnore in minified apps by changing the `HeapIgnore` component to a class, explicitly set the component's `displayName`, and check against the class's displayName, rather than a string literal.
Manually tested on a minified app.

[HEAP-15381] Improve Support for HeapIgnore in minified apps [S]

---

CHANGELOG.md
ios/Vendor/Heap.h

Upgrade the native Heap iOS dependency to 6.8.1.
Existing e2e tests.
This was tested as a commit on top of https://github.com/heap/react-native-heap/pull/192, and was then cherry-picked onto a branch off of develop.  https://github.com/heap/react-native-heap/pull/192 needs additional work, so opening a PR for this off of develop even though tests don't run for me locally (Catalina, Xcode 11).

[HEAP-16088] Upgrade native iOS Heap dependency to 6.8.1 [S]

---

CHANGELOG.md
index.d.ts

Add types for `HeapIgnore` to type declarations.
Created a typescript file and confirmed `tsc`

[HEAP-15357] Update index.d.ts with HeapIgnore types

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/ios/TestDriver.xcodeproj/project.pbxproj
examples/TestDriver/package.json
package-lock.json
package.json

Bump version to 0.12.0 for release.
Detox passes for Android.  iOS tests pass by cherry-picking this commit onto https://github.com/heap/react-native-heap/pull/192 and running iOS detox tests.

Bump version to 0.12.0

---

react-native-heap.podspec

Fixes the following build error (React 0.62.2)
```
Undefined symbols for architecture x86_64:
"_SCNetworkReachabilityGetFlags", referenced from:
-[HeapReachability connectionRequired] in libHeap.a(HeapReachability.o)
-[HeapReachability currentReachabilityStatus] in libHeap.a(HeapReachability.o)
"_SCNetworkReachabilityCreateWithAddress", referenced from:
+[HeapReachability reachabilityWithAddress:] in libHeap.a(HeapReachability.o)
"_SCNetworkReachabilityCreateWithName", referenced from:
+[HeapReachability reachabilityWithHostName:] in libHeap.a(HeapReachability.o)
"_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
-[HeapReachability startNotifier] in libHeap.a(HeapReachability.o)
"_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
-[HeapReachability stopNotifier] in …
```

fix: add SystemConfiguration framework to .podspec

---

examples/TestDriver/android/app/build.gradle

Add the local endpoint configuration for the Android event visualizer to the TestDriver build config.  This allows local Android EV dev work to be done for React Native events.

Add local EV endpoint to TestDriver Android build config [XS]

---

CHANGELOG.md
instrumentor/src/index.js
instrumentor/test/fixtures/is-not-pressability/code.js
instrumentor/test/fixtures/is-not-pressability/output.js
instrumentor/test/fixtures/is-pressability/code.js
instrumentor/test/fixtures/is-pressability/output.js
instrumentor/test/index.js
js/Heap.js
js/autotrack/__tests__/common.spec.js
js/autotrack/common.ts
js/autotrack/scrollViews.js
js/autotrack/switches.js
js/autotrack/textInput.js
js/autotrack/touchables.js

Touchable support for React Native 0.62+.
This involves adding instrumentation to the new RN Pressability class's constructor, copying the config, and wrapping the config's onPress and onLongPress methods.
This PR is intended for an alpha release, so testing isn't as good as it should be.  These two commits were cherry-picked from https://github.com/heap/react-native-heap/pull/198 to keep develop clean.
Still need to run detox tests for <0.62 by cherry-picking these commits onto https://github.com/heap/react-native-heap/pull/192, but otherwise ready for review.
Detox tests for android pass for the 0.62 app on https://github.com/heap/react-native-heap/pull/198, but a detox issue is preventing iOS tests from running.  Because this only changes instrumentation on the JS side, test results …

[HEAP-16352] Alpha support for Touchables in React Native 0.62+

---

examples/TestDriver/package.json
package-lock.json
package.json

Bump version to 0.13.0-alpha1 for the RN 0.62 support changes.
Since this is only an alpha, and the TestDriver iOS test app isn't currently working on my machine (Catalina), I only ran Android detox tests.

[HEAP-16697] Bump version to 0.13.0-alpha1

---

js/__tests__/Heap.spec.js
js/autotrack/__tests__/common.spec.js
js/util/metadataPropUtil.ts

Include a `react_native_version` telemetry metadata prop on React Native events.  Note that this will _not_ work on React Native versions below 0.61, since that's the first version with the `Platform.constants` API (see tags associated with https://github.com/facebook/react-native/commit/7fd08e146184432731ec5d5ba210e352690dc569).
* Ran Android e2e tests to confirm this doesn't lead to any regressions on older versions of RN.
* Ran this on an android app with a newer version of React Native, and confirmed that `react_native_version` is included as a source property with an accurate value.

Include react native version with other telemetry props [S]

---

instrumentor/src/index.js
instrumentor/test/fixtures/is-touchable-0-62/output.js

In some cases (most likely just isolated unit tests), `require('@heap/react-native-heap').default` will be undefined.  Currently, we do not handle this case, so tests in which this happens end up crashing.
Instead, stub out the method with a no-op for that particular HOC.  For example, instead of
```
const Heap = require('@heap/react-native-heap').default;
const TouchableOpacity = Heap.withHeapTouchableAutocapture(class Touchable Opacity {...});
```
we would get
```
const Heap = require('@heap/react-native-heap').default || {
withHeapTouchableAutocapture: (Component) => Component,
};
const TouchableOpacity = Heap.withHeapTouchableAutocapture(class Touchable Opacity {...});
```
such that the HOC will simply return the original component.
I couldn't get a local repro of …

[HEAP-16942] No-op when Heap is undefined in instrumentor

---

examples/TestDriver/package.json
package-lock.json
package.json

Bump version to 0.13.0-alpha2 with a fix related to RN 0.62 support changes.
Since this is only an alpha, and the TestDriver iOS test app isn't currently working on my machine (Catalina), I only ran Android detox tests.

[HEAP-16942] Bump version to 0.13.0-alpha2

---

CHANGELOG.md
examples/TestDriverRN063/package-lock.json
examples/TestDriverRN063/src/screens/NavigationScreen.tsx
examples/TestDriverRN063/src/screens/navigationScreens/StackNavigationScreen.tsx
examples/TestDriverRN063/src/screens/navigationScreens/TabNavigationScreen.tsx
js/autotrack/reactNavigation.js
js/util/navigationUtil.ts

Due to API changes between v4 and v5 of the React Navigation library, our `withReactNavigationAutotrack` HOC would not work for apps running React Navigation 5.  This PR adds support for React Navigation 5.
Ran E2E detox tests on Android to test for regressions on React Navigation 3/4.
TODO: Manual testing of React Navigation 5 on the new test app.

[HEAP-16909] React Navigation 5 Support

---

CHANGELOG.md
examples/TestDriverRN063/package-lock.json
examples/TestDriverRN063/src/screens/TouchablesScreen.tsx
instrumentor/src/index.js
instrumentor/test/fixtures/is-functional-textinput/code.js
instrumentor/test/fixtures/is-functional-textinput/output.js
instrumentor/test/index.js
js/Heap.js
js/autotrack/textInput.js

This is similar to https://github.com/heap/react-native-heap/pull/207 in that it adds HOC-based instrumentation for `TextInput` components.
Starting with RN 0.62, the internal implementation of the React Native `TextInput` component uses a functional component and React Hooks (this used to be a stateful class component).  Because of this, support for this component in RN 0.62+ would require new instrumentation (not as complicated as non-HOC `Touchable` support, but still non-trivial), making this instrumentation fix a candidate for the HOC-based instrumentation approach.
The instrumentation looks for a function named `InternalTextInput` and wraps it with an HOC.  I.e.
```
function InternalTextInput(props: Props): React.Node {}
```
becomes
```
const Heap = …
```

HOC instrumentation for TextInput on RN 0.62+

---

instrumentor/src/index.js
instrumentor/test/fixtures/is-function-declaration-no-id/code.js
instrumentor/test/fixtures/is-function-declaration-no-id/output.js
instrumentor/test/index.js

Fixes a bug introduced with the TextInput HOC-based instrumentation in which the presence of a `FunctionDeclaration` without an `id` (as is the case for declarations like `export default function() {}`) would cause the instrumentor to crash.
Check whether `id` on `FunctionDeclaration`s is present, and add tests for this case.
- Added instrumentor test case
- Ran Android detox tests

[HEAP-17696] Fix instrumentation build failure on id-less function declarations

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
examples/TestDriverRN063/ios/Podfile.lock
examples/TestDriverRN063/package-lock.json
examples/TestDriverRN063/package.json
package-lock.json
package.json

Bump version to 0.13.0.
Manually tested on new RN 0.63 test app, and ran Android detox test on old test app.

[HEAP-17481] Bump version to 0.13.0 (stable)

---

CHANGELOG.md
ios/Vendor/Heap.h

Upgrade iOS Heap SDK dependency to v7.2.0.
Manually tested iOS on new test app.

[HEAP-17331] Upgrade iOS Heap dependency to 7.2.0

---

CHANGELOG.md
examples/TestDriverRN063/package-lock.json
examples/TestDriverRN063/src/screens/TouchablesScreen.tsx
js/autotrack/textInput.js

This was surfaced in https://github.com/heap/react-native-heap/pull/208#issuecomment-691510590 after that PR was merged (thanks @emodventures!).
The specific issue is that the react native lib itself does some ref-forwarding for TextInput (https://github.com/facebook/react-native/blob/4a6039c6359ba70f5cca57ceff26c06f2a0de76b/Libraries/Components/TextInput/TextInput.js#L1172), so the `forwardedRef` prop used by the Heap lib's HOC to forward refs was effectively overwriting the `forwardedRef` prop passed into the HOC by the React Native lib.
By changing the name of `forwardedRef` to the namespaced prop `heapForwardedRef`, we'll still handle _direct_ refs to the `InternalTextInput` passed by the RN lib (e.g. if the RN lib did `<InternalTextInput ref={myRef} />`), while allowing _forwarded_ …

Fix ref-forwarding on TextInput HOC for RN 0.62+

---

CHANGELOG.md
examples/TestDriverRN063/ios/TestDriverRN063/AppDelegate.m
examples/TestDriverRN063/package-lock.json
ios/HeapSettings.bundle/HeapSettings.plist.template
ios/HeapSettings.bundle/generate_settings.rb
ios/HeapSettings.bundle/generate_settings_common.rb
ios/HeapSettings.bundle/generate_settings_non_cocoapods.rb
ios/RNHeapInit.m

Add an `enableNativeTouchEventCapture` option for `heap.config.json` that defaults to `false`.  This flag determines whether events captured by the native iOS SDK (which are generally superfluous to events captured by the RN SDK, and are almost always unusable) will be processed.  This is intended to replace the need for `heapIgnore` as described in the [React Native iOS install docs](https://developers.heap.io/docs/react-native#ios-1) while ensuring that views created outside the root view (as is the case for certain modals) will also be ignored by the native iOS SDK.
In cases where parts of an app are implemented as native iOS views, `enableNativeTouchEventCapture` should be set to true, and `heapIgnore` should still be set on the root view.
This feature builds on the functionality …

[HEAP-17331] Disable native iOS capture by default

---

e2e/basics.spec.js
examples/TestDriver/android/app/build.gradle
examples/TestDriver/android/app/src/androidTest/java/com/testdriver/DetoxTest.java
examples/TestDriver/package.json
package.json

- Broken Android E2E test harness.
- No.
- No.
- Was able to get Android E2E tests to build and pass.
- No.
Was there manual …

Rn android/fix/heap 20927 try test harness

---

CHANGELOG.md
js/autotrack/common.ts

This add support for React 17. It does this by checking for both the new and old fiber internal value and using the correct one. It should be backwards compatible, but I have currently not tested it on older versions of React.
Fixes #241

React 17 Support

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
examples/TestDriverRN063/ios/Podfile.lock
examples/TestDriverRN063/package.json
package-lock.json
package.json

- Add support for React 17
- No
- No
- Manually, with a local iOS simulator and local Android emulator against Heap production
- No …

[HEAP-23268] Bump version to 0.16.0

---

instrumentor/src/index.js
instrumentor/test/fixtures/is-functional-textinput/output.js
instrumentor/test/fixtures/is-touchable-0-62/output.js

This is _potentially_ a fix for the `Cannot read property 'end' of null` issues we've been seeing, which could end up being a fix for the `assembleRelease` issue.
I'm not 100% confident this works because of our test suite, but I poked around the app manually and this seems to fix the problem for HOC instrumentation. Here's a quick overview of the steps I took here:
- I commented out instrumentation functions in `instrumentor/index.js` one by one to determine the smallest set of instrumentation types that causes the issue. This turned out to be `instrumentTextInputHoc` and `instrumentTouchableHoc`.
- Each of these functions ends with a call to `replaceWithMultiple`. From the [handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#replacing-a- …

Attempt to fix sporadic babel transpile issues

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
examples/TestDriverRN063/ios/Podfile.lock
examples/TestDriverRN063/package.json
package-lock.json
package.json

- This alpha release just contains https://github.com/heap/react-native-heap/pull/256 at this point
- Release guide: https://heapinc.atlassian.net/wiki/spaces/ENG/pages/16222507/Publishing+react-native-heap+to+npm
This change was manually tested against 0.63 but no automated testing has been applied

[HEAP-23436] Bump version to 0.17.0-alpha1

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
ios/HeapSettings.bundle/generate_settings_common.rb
package-lock.json
package.json

This fixes a bug in ios/HeapSettings.bundle/generate_settings_common.rb, reported in #272, which broke iOS autocapture.
Ironically, this bug was introduced with testing code and not caught because automated testing wouldn't exercise the unset state.  Unit testing would be a good idea if we touch this again, generating a few different versions of the settings bundle and validating the `HeapOptions` that are outputted.
This change was tested manually by adding the packed zip to a simple project and trying different permutations of heap.config.json.

iOS hotfix 0.17.1

---

integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json

@bnickel PTAL. I actually suspect this might not be 100% what we want. Since 0.17.1 is a released version, it probably makes sense to have the TestDriver* apps use a snapshot like `0.17.2-SNAPSHOT` which would be located on disk. What do you think?
Changes:
- integration-tests/drivers/TestDriver063/package-lock.json: Reran `npm install` to bring package-lock Heap version to 0.17.1 which is the current value in package.json.
- integration-tests/drivers/TestDriver066/package.json: Updated package.json version of Heap to 0.17.1.
- integration-tests/drivers/TestDriver063/package-lock.json: Reran `npm install` to bum
p package-lock Heap version to 0.17.1.
Thanks for using Heap's React Native SDK! If you're having any issues, please reach out to customer support at <support@heap.io>. For the …

RN: Fix Heap versions in test drivers

---

CHANGELOG.md
react-native-heap.podspec

The title says it all. The build script worked in `/Users/Brian/Project`, but not `/Users/Brian/My Project`.
I used the integration-tests folder  and added a space in the name.  Running `npx react-native run-ios` failed without the fix and passed with it.

Fix iOS build script in directories with spaces

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
package.json

- Fixed iOS build in folders with spaces.
- Fixed minSdkVersion build error on React Native 0.64+.

0.18.0 Release

---

integration-tests/drivers/TestDriver063/ios/overwrite-heap.sh

After experimenting with Cocoapods and relearning its deficiencies, I've come up with a simple script for testing local Heap changes in the TestDriver063 project.  The added script simply changes directories into the Heap project, builds the SDK and then copies it over `ios/Pods/Heap/Heap.xcframework`.  Crude but it gets the job done.
My _current_ process for testing Heap.xcframework changes with this is:
**Setup**
1. `cd integration-tests && ./test.sh drivers/TestDriver063 ios`
2. Let it run.
3. Edit `heap.config.json` as needed.
**Testing**
1. Make whatever changes I need in the **Heap project**.
2. `cd drivers/TestDriver063/ios`
3. `./overwrite-heap.sh` to install the changes.
4. `open TestDriver063.xcworkspace`, run the project in the simulator.
5. Rebuild and run the project.

Added a script for overwriting Heap.xcframework locally

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
package-lock.json
package.json

- Added support for Event Visualizer on iOS, with a pairing option in the React Native developer menu.
- Added iOS-only option to enable Heap SDK debug logging in the iOS console, enabled by default on dev builds.
- Disabled tracking of view controllers on iOS when `enableNativeTouchEventCapture` is off.
- Updated `Heap.setAppId` on iOS to turn off native touch capture on iOS.
- Updated `Heap.setAppId` on iOS to enable logging on debug builds.

0.19.0 Release

---

CHANGELOG.md
index.d.ts

Fixes #277.
The type definition was overly prescriptive and produced a type error on React Native 6.  This is just something that creates an element.

Be less prescriptive about NavigationContainer typing

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
package-lock.json
package.json

- Upgraded the Android library to use Heap version 1.10.+
- Fixed type definition for `withReactNavigationAutotrack` on React Navigation 6.

0.20.0 Release

---

CHANGELOG.md
__mocks__/react-native.js
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
index.d.ts
integration-tests/src/screens/PropertiesScreen.tsx
integration-tests/tests/heap_properties.e2e.js
integration-tests/tests/util/server.ts
integration-tests/tests/util/types.ts
ios/RNHeap.m
js/Heap.js
js/__tests__/Heap.spec.js

adds `getSessionId` method to return the current session id.
tests - they only partially ran locally but the mock tests seemed fine. Also this is mostly a copy and paste of `getUserId` but the difference with `getSessionId` is …

[HEAP-28313] implement getSessionId

---

CHANGELOG.md
android/build.gradle
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
integration-tests/drivers/TestDriver063/android/build.gradle
integration-tests/drivers/TestDriver063/android/gradle.properties
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/ios/TestDriver063.xcodeproj/project.pbxproj
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
integration-tests/tests/heap_properties.e2e.js
integration-tests/tests/util/server.ts
integration-tests/tests/util/types.ts

[HEAP-37545](https://heapinc.atlassian.net/browse/HEAP-37545) [HEAP-37544](https://heapinc.atlassian.net/browse/HEAP-37544)
This resolves two issues with this project on Android:
1. It fixes a compiler error introduced in #327.
2. It removes `jcenter` in favor of `mavenCentral` since jcenter is EOL.
In fixing the first issue, I switched from `android.util.Log` to `RNLog`, which will present the warning in the Metro and debug builds.  I also went through some hoops to get the tests working again since the React Native versions they were using broke on November 4.
- The tests have compiled and run with the fixes.
- I have validated that the message gets displayed Metro on a test build.
Fixes #312, #334, #335, #342, #347,  #348.

[HEAP-37545][HEAP-37544] Fix Android build and move off of jcenter

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
js/version.ts
package-lock.json
package.json

[HEAP-46713](https://heapinc.atlassian.net/browse/HEAP-46713)
- Fixed `<Switch>` change event capture on React Native 0.66 and later.
[HEAP-46713]: https://heapinc.atlassian.net/browse/HEAP-46713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HEAP-46713] Release 0.22.4

---

CHANGELOG.md
js/__tests__/Heap.spec.js
js/autotrack/reactNavigation.js

If `Heap.withHeapNavigationWrapper` is called multiple times, it currently returns a new HOC each time.  This means if the app looks like this:
```
const App = () => {
...
const HeapNavigationContainer =
Heap.withReactNavigationAutotrack(NavigationContainer);
return (
<HeapNavigationContainer independent={true}>
...
</HeapNavigationContainer>
);
};
```
And the app contains a `useEffect` or similar, which caused `App` to re-evaluate, the entire contents of `HeapNavigationContainer` will be considered new and will be recreated, sending the app back to start.
The general fix is to move `Heap.withHeapNavigationWrapper` out of a function but this has come up enough that a code fix is warranted.
This simply caches the output of `withReactNavigationAutotrack` on the wrapped component so it can …

[HEAP-42725] Return the same component each time from `withHeapNavigationWrapper`

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
js/version.ts
package-lock.json
package.json

- `Heap.withHeapNavigationWrapper` returns the same object when called multiple times, preventing app refreshes when used within a re-evaluated function like `App` with `useEffect`.
- The typescript definition for `<HeapIgnore/>` has been updated to support React 18.
- Podspec now produces a stable checksum in Podfile.lock across machines.

[HEAP-42725] Release 0.22.5

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
js/version.ts
package-lock.json
package.json

This removes explicit babel dependencies from package.json to fix audit issues.  The dependencies were pulled in to support the Babel plugin, but Babel plugins don't actually need dependencies since they are provided by Babel during execution.
No code changes but Detox was run.

[PA-2258] Release 0.22.7 with babel-traverse fix
