heap/react-native-heap

index.d.ts

Based this off of the documentation at: https://docs.heapanalytics.com/reference

Add typings for Typescript

---

package.json

Adds ts bindings to npm bundle and bumps version.

---

js/Heap.js

Determine target text by concatenating target texts of component children, and include it in the autotracked event.

Capture target text on autotrack events

---

examples/TestDriver/src/mainScreen.js

This change is from internal repo, but wasn't merged before the TestDriver app was copied over.

Add text component to TestDriver for target text testing

---

.gitignore
js/util/combineConfigs.ts
package-lock.json
package.json
tsconfig.json

Also removes a library which was misbehaving with the TS build system (`typescript-collections`)

Add a TS Build to support earlier versions of RN

---

examples/TestDriver/ios/Podfile.lock
examples/TestDriver/ios/TestDriver.xcodeproj/project.pbxproj

These changes were created when I ran `pod install` in `TestDriver/iOS`. The main thing to verify here is whether these are legitimate changes or problems with my local setup.

Updates to the iOS `TestDriver` app.

---

js/util/extractProps.ts

This was missed in a previous commit and is causing CI to fail on other PRs.

Fix prettier lint

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
package-lock.json
package.json

[HEAP-8725] Release version 0.3.0.

---

CHANGELOG.md

https://heap.slack.com/archives/GHT0NG6CA/p1556047743004200

Add release dates to the two most recent releases in CHANGELOG.md

---

js/util/__tests__/combineConfigs.spec.ts
js/util/__tests__/extractProps.spec.ts
js/util/bailer.ts
js/util/combineConfigs.ts
js/util/extractProps.ts
tsconfig.json

Read more: https://mariusschulz.com/blog/typescript-2-3-the-strict-compiler-option

TypeScript: Strict Mode

---

e2e/heapIgnore.spec.js
examples/TestDriver/src/pages/basics.js
examples/TestDriver/src/pages/heapIgnore.js
examples/TestDriver/src/topNavigator.js

Detox tests for HeapIgnore on the TestDriver app.

[HEAP-9165] HeapIgnore e2e tests

---

js/libraryPropConfigs/rnElementsPropConfig.ts
js/propExtractorConfig.ts

Built-in props for the React Native Elements component library.

[HEAP-9594] Add RN Elements builtin prop config

---

js/libraryPropConfigs/nativeBasePropConfig.ts
js/propExtractorConfig.ts

Built-in props for the NativeBase component library.

[HEAP-9597] Add NativeBase default prop config

---

examples/TestDriver/src/navigatorService.js

This should have been included in https://github.com/heap/react-native-heap/pull/101 but didn't make it in.

Add uncommitted navigatorService file

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
package-lock.json
package.json

[HEAP-9659] Bump version to 0.5.0

---

android/build.gradle
ios/Vendor/Heap.h

Bump iOS to v6.2.0.
Bump Android to v1.1.0

[HEAP-10084] Upgrade native lib versions

---

CHANGELOG.md
__mocks__/react-native.js
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
e2e/basics.spec.js
examples/TestDriver/src/pages/basics.js
ios/RNHeap.m
js/Heap.js
js/__tests__/Heap.spec.js

Add the `resetIdentity` method to the bridge + add tests.

[HEAP-9795] Reset Identity

---

js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/heapIgnore.js

Forward references passed to the HeapIgnore HOC.

[HEAP-9669] Ref-forwarding on HeapIgnore HOC

---

e2e/basics.spec.js
examples/TestDriver/src/pages/basics.js
instrumentor/src/index.js
instrumentor/test/fixtures/is-text-input/code.js
instrumentor/test/fixtures/is-text-input/output.js
instrumentor/test/fixtures/not-text-input/code.js
instrumentor/test/fixtures/not-text-input/output.js
instrumentor/test/index.js
js/Heap.js
js/autotrack/textInput.js

Implement per the [RFC](https://paper.dropbox.com/doc/miniRFC-React-Native-TextInput-Capture--AidTkeTtTn8Gk_7KQ7qnPeJDAg-0877UPqDFpKmZX67QPcp1)

[HEAP-10401] Implement TextInput instrumentation

---

android/build.gradle

Enables build with other Java8 components e.g. https://github.com/wix/Detox

enable build with java 8 components

---

CHANGELOG.md

Update changelog for RNFCL
N/A

[HEAP-11564] Update changelog

---

README.md

Update README.md to point to the main docs.

[HEAP-11365] Update usage section in README with link to docs

---

CHANGELOG.md
android/build.gradle
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
e2e/basics.spec.js
e2e/heapIgnore.spec.js
e2e/nav.spec.js
e2e/propExtraction.spec.js
e2e/rnTestUtilities.js
examples/TestDriver/App.js
examples/TestDriver/android/build.gradle
examples/TestDriver/src/pages/basics.js
instrumentor/src/index.js
instrumentor/test/fixtures/is-scroll-view-createreactclass/output.js
instrumentor/test/fixtures/is-scroll-view-extends-component/output.js
instrumentor/test/fixtures/is-switch/output.js
instrumentor/test/fixtures/is-text-input/output.js
ios/RNHeap.m
ios/Vendor/Heap.h
js/Heap.js
js/__tests__/Heap.spec.js
js/autotrack/__tests__/heapIgnore.spec.js
js/autotrack/common.ts
js/autotrack/reactNavigation.js
js/autotrack/scrollViews.js
js/autotrack/textInput.js
js/autotrack/touchables.js
js/util/__mocks__/navigationUtil.js
js/util/navigationUtil.ts

All RNFCL changes.  Each commit was already reviewed as a PR, so this just needs a rubber stamp.
This will be merge-committed (not squash-merged) to maintain commit history.
~Blocked on https://github.com/heap/react-native-heap/pull/160~ this has been merged
See PRs.

[HEAP-11800] RNFCL

---

CHANGELOG.md

Add link to RNFCL upgrade guide to changelog

Add 0.9.0 upgrade guide link to changelog

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
package-lock.json
package.json

Bump version to 0.10.0

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
package-lock.json
package.json

[HEAP-14089] Bump to 0.11.0

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
examples/TestDriverRN063/ios/Podfile.lock
examples/TestDriverRN063/ios/TestDriverRN063/AppDelegate.m
examples/TestDriverRN063/package-lock.json
examples/TestDriverRN063/package.json
examples/TestDriverRN063/src/screens/TouchablesScreen.tsx
ios/HeapSettings.bundle/HeapSettings.plist.template
ios/HeapSettings.bundle/generate_settings.rb
ios/HeapSettings.bundle/generate_settings_common.rb
ios/HeapSettings.bundle/generate_settings_non_cocoapods.rb
ios/RNHeapInit.m
ios/Vendor/Heap.h
js/autotrack/textInput.js
package-lock.json
package.json

Cut release

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
examples/TestDriverRN063/ios/Podfile.lock
examples/TestDriverRN063/package.json
js/autotrack/common.ts
package-lock.json
package.json

- Add support for React 17
- No
- No
- Manual tests on a local iOS simulator and local Android emulator against production servers
- …

Cut release for 0.16.0

---

CHANGELOG.md
examples/TestDriver/ios/Podfile.lock
examples/TestDriver/package.json
examples/TestDriverRN063/ios/Podfile.lock
examples/TestDriverRN063/package.json
instrumentor/src/index.js
instrumentor/test/fixtures/is-functional-textinput/output.js
instrumentor/test/fixtures/is-touchable-0-62/output.js
package-lock.json
package.json

- Fixed sporadic Babel instrumentation (`Cannot read property 'end' of null`) issues.
No.
No.
Manually against test app.
No.
Was …

Cut release for 0.17.0-alpha1

---

CHANGELOG.md
react-native-heap.podspec

----
* Updated ios version to 9.0
Was there manual testing?

[HEAP-33205] Bump IOS version

---

CHANGELOG.md
package-lock.json
package.json

Updated to version 0.22.0

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
package-lock.json
package.json

- Switched repositories from jcenter to mavenCentral.
- Fixed Android compilation, moving log to `RNLog.w`.

0.22.1 Release

---

CHANGELOG.md
android/build.gradle
android/src/main/java/com/heapanalytics/reactnative/RNHeapLibraryModule.java
integration-tests/drivers/TestDriver063/android/build.gradle
integration-tests/drivers/TestDriver063/android/gradle.properties
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/ios/TestDriver063.xcodeproj/project.pbxproj
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
integration-tests/tests/heap_properties.e2e.js
integration-tests/tests/util/server.ts
integration-tests/tests/util/types.ts
package-lock.json
package.json

Cut 0.22.1 Release

---

CHANGELOG.md
integration-tests/drivers/TestDriver063/ios/Podfile.lock
integration-tests/drivers/TestDriver063/package-lock.json
integration-tests/drivers/TestDriver063/package.json
integration-tests/drivers/TestDriver066/ios/Podfile.lock
integration-tests/drivers/TestDriver066/package-lock.json
integration-tests/drivers/TestDriver066/package.json
js/version.ts
package-lock.json
package.json

[HEAP-45444](https://heapinc.atlassian.net/browse/HEAP-45444)
This releases a fix for the critical vulnerabilities around xmldom.
[HEAP-45444]: https://heapinc.atlassian.net/browse/HEAP-45444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HEAP-45444] Release 0.22.3
